module tests.maths;

math.sin(4.5);
math.sin(5);
try math.sin('h'); catch(e){}
math.abs(4.5);
math.abs(5);
try math.abs('h'); catch(e){}
math.cos(5);
math.tan(5);
math.asin(5);
math.acos(5);
math.atan(5);
math.atan2(4, 5);
math.sqrt(5);
math.cbrt(5);
math.exp(5);
math.ln(5);
math.log2(5);
math.log10(5);
math.hypot(4, 5);
math.lgamma(5);
math.gamma(5);
math.ceil(5);
math.floor(5);
math.round(5);
math.trunc(5);
math.isNan(5);
math.isInf(5);
math.sign(5);
math.sign(-5);
math.sign(0);
math.sign(5.0);
math.sign(-5.0);
math.sign(0.0);
math.pow(5, 4.5);
math.pow(5, 5);
math.rand();
math.rand(10);
math.rand(10, 20);